{{- if and .Values.k8sGateway.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8sGateway.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gateways
  - httproutes
  - tcproutes
  - gatewayclasses
  verbs: ["watch", "list"]
- apiGroups: ["k8s.nginx.org"]
  resources: ["*"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8sGateway.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8sGateway.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "blocky.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
