{{- if .Values.k8sGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sGateway.fullname" . }}
  labels:
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
    {{- include "blocky.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
  annotations:
{{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "blocky.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  ports:
  - port: {{ .Values.k8sGateway.service.port }}
    protocol: UDP
    name: dns-udp
    targetPort: dns-udp
  {{- if (eq .Values.k8sGateway.service.useTcp true) }}
  - port: {{ .Values.k8sGateway.service.port }}
    protocol: TCP
    name: dns-tcp
    targetPort: dns-tcp
  {{- end }}
{{- end }}